/* eslint-disable @typescript-eslint/no-explicit-any */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Blender3D (https://sketchfab.com/Blender3D)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/0d62f4d3676545c88ec8523213c055dd
title: Minecraft Diamond Axe
*/

import { useGLTF } from '@react-three/drei';
import pickUrl from './assets/pick.glb?url';
import axeUrl from './assets/axe.glb?url';
import { AXE_DATA, PICK_DATA, ToolType } from './data/data';

export default function Tool({ type = 'pick' }: { type: ToolType }) {
  const { scene: pickScene } = useGLTF(pickUrl);
  const { scene: axeScene } = useGLTF(axeUrl);

  const position = type === 'axe' ? AXE_DATA.position : PICK_DATA.position;
  const scale = type === 'axe' ? AXE_DATA.scale : PICK_DATA.scale;
  const rotation = type === 'axe' ? AXE_DATA.rotation : PICK_DATA.rotation;
  const scene = type === 'axe' ? axeScene : pickScene;

  return (
    <group dispose={null} position={position} scale={scale}>
      <group rotation={rotation}>
        <primitive object={scene} color="white" />
      </group>
    </group>
  );
}

useGLTF.preload(axeUrl);
useGLTF.preload(pickUrl);
